/// File generated by FlutterFire CLI.[FlutterFire CLI tarafından oluşturulan dosya.]
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.[Firebase uygulamalarınızla kullanmak için varsayılan [FirebaseOptions]
///
/// Example:[Örnek]
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkh3ULxJixHl1OsjmfIDqnpiqNTriH--0',
    appId: '1:572901578769:web:fc7bdbad7f2b75cec3b9b0',
    messagingSenderId: '572901578769',
    projectId: 'shinex-a38ea',
    authDomain: 'shinex-a38ea.firebaseapp.com',
    storageBucket: 'shinex-a38ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGPS6eWMLU4HVX7U5eOpGnLLGpZEuIzhM',
    appId: '1:572901578769:android:bb2d08099b85e5e2c3b9b0',
    messagingSenderId: '572901578769',
    projectId: 'shinex-a38ea',
    storageBucket: 'shinex-a38ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2WNRw2Eq7ytcDxLeW4xHK_Z13xtPq8Yg',
    appId: '1:572901578769:ios:ae11507dfe0a2226c3b9b0',
    messagingSenderId: '572901578769',
    projectId: 'shinex-a38ea',
    storageBucket: 'shinex-a38ea.appspot.com',
    iosBundleId: 'com.example.shinex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2WNRw2Eq7ytcDxLeW4xHK_Z13xtPq8Yg',
    appId: '1:572901578769:ios:ae11507dfe0a2226c3b9b0',
    messagingSenderId: '572901578769',
    projectId: 'shinex-a38ea',
    storageBucket: 'shinex-a38ea.appspot.com',
    iosBundleId: 'com.example.shinex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkh3ULxJixHl1OsjmfIDqnpiqNTriH--0',
    appId: '1:572901578769:web:b139674000913e88c3b9b0',
    messagingSenderId: '572901578769',
    projectId: 'shinex-a38ea',
    authDomain: 'shinex-a38ea.firebaseapp.com',
    storageBucket: 'shinex-a38ea.appspot.com',
  );

}