/// File generated by FlutterFire CLI.[FlutterFire CLI tarafından oluşturulan dosya.]
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.[Firebase uygulamalarınızla kullanmak için varsayılan [FirebaseOptions]
///
/// Example:[Örnek]
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqNgakWTcTpD5IfIMkJ2AIhVdiNrCum24',
    appId: '1:876652083302:web:0867be52d9391e280ed5a7',
    messagingSenderId: '876652083302',
    projectId: 'shinex-61a9d',
    authDomain: 'shinex-61a9d.firebaseapp.com',
    storageBucket: 'shinex-61a9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG_xF5y7TyW-WeVHCAjyvZ7QvLA2POhaE',
    appId: '1:876652083302:android:407b4ffad1456a960ed5a7',
    messagingSenderId: '876652083302',
    projectId: 'shinex-61a9d',
    storageBucket: 'shinex-61a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWnPLKSPguEtX290FjGcMgK_c3JXNt3Uw',
    appId: '1:876652083302:ios:17c9c79416df7d6a0ed5a7',
    messagingSenderId: '876652083302',
    projectId: 'shinex-61a9d',
    storageBucket: 'shinex-61a9d.appspot.com',
    androidClientId: '876652083302-ve80gj545a7sk50bctj38vctq23aehs0.apps.googleusercontent.com',
    iosClientId: '876652083302-inl4lknimk69c7ledg406fjtp715plno.apps.googleusercontent.com',
    iosBundleId: 'com.example.shinex',
  );
}
